CREATE SCHEMA SPRING;

USE SPRING;

CREATE TABLE USR_USUARIO (
  USR_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USR_NOME VARCHAR(20) NOT NULL,
  USR_SENHA VARCHAR(50) NOT NULL,
  CONSTRAINT USR_USUARIO_PK PRIMARY KEY (USR_ID),
  CONSTRAINT USR_NOME_UK UNIQUE KEY (USR_NOME)
);

CREATE TABLE PER_PERFIL (
  PER_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  PER_NOME VARCHAR(20) NOT NULL,
  CONSTRAINT PER_PERFIL_PK PRIMARY KEY (PER_ID),
  CONSTRAINT PER_NOME_UK UNIQUE KEY (PER_NOME)
);

CREATE TABLE AUT_AUTORIZACAO (
  AUT_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  AUT_NOME VARCHAR(20) NOT NULL,
  CONSTRAINT AUT_AUTORIZACAO_PK PRIMARY KEY (AUT_ID),
  CONSTRAINT AUT_NOME_UK UNIQUE KEY (AUT_NOME)
);

CREATE TABLE USP_USUARIO_PERFIL (
  USR_ID BIGINT UNSIGNED NOT NULL,
  PER_ID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (USR_ID, PER_ID),
  FOREIGN KEY USP_USUARIO_FK (USR_ID) REFERENCES USR_USUARIO (USR_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY USP_PERFIL_FK (PER_ID) REFERENCES PER_PERFIL (PER_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE PEA_PERFIL_AUTORIZACAO (
  PER_ID BIGINT UNSIGNED NOT NULL,
  AUT_ID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (PER_ID, AUT_ID),
  FOREIGN KEY PEA_PERFIL_FK (PER_ID) REFERENCES PER_PERFIL (PER_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY PEA_AUTORIZACAO_FK (AUT_ID) REFERENCES AUT_AUTORIZACAO (AUT_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

INSERT INTO USR_USUARIO(USR_NOME, USR_SENHA) VALUES('teste', MD5('teste'));
INSERT INTO USR_USUARIO(USR_NOME, USR_SENHA) VALUES('admin', MD5('admin'));
INSERT INTO PER_PERFIL(PER_NOME) VALUES('Usuário');
INSERT INTO PER_PERFIL(PER_NOME) VALUES('Vendedor');
INSERT INTO PER_PERFIL(PER_NOME) VALUES('Administrador');
INSERT INTO AUT_AUTORIZACAO(AUT_NOME) VALUES('ROLE_VENDA');
INSERT INTO AUT_AUTORIZACAO(AUT_NOME) VALUES('ROLE_USUARIO');
INSERT INTO AUT_AUTORIZACAO(AUT_NOME) VALUES('ROLE_FINANCEIRO');
INSERT INTO AUT_AUTORIZACAO(AUT_NOME) VALUES('ROLE_CONSULTA');
INSERT INTO AUT_AUTORIZACAO(AUT_NOME) VALUES('ROLE_ASSOCIADO');
INSERT INTO AUT_AUTORIZACAO(AUT_NOME) VALUES('ROLE_PRODUTO');
INSERT INTO AUT_AUTORIZACAO(AUT_NOME) VALUES('ROLE_PERFIL');
INSERT INTO USP_USUARIO_PERFIL(USR_ID, PER_ID)
SELECT USR_ID, PER_ID
FROM USR_USUARIO, PER_PERFIL
WHERE USR_NOME = 'teste'
AND PER_NOME IN ('Usuário', 'Vendedor');
INSERT INTO USP_USUARIO_PERFIL(USR_ID, PER_ID)
SELECT USR_ID, PER_ID
FROM USR_USUARIO, PER_PERFIL
WHERE USR_NOME = 'admin'
AND PER_NOME = 'Administrador';
INSERT INTO PEA_PERFIL_AUTORIZACAO(PER_ID, AUT_ID)
SELECT PER_ID, AUT_ID
FROM PER_PERFIL, AUT_AUTORIZACAO
WHERE PER_NOME = 'Usuário'
AND AUT_NOME = 'ROLE_PRODUTO';
INSERT INTO PEA_PERFIL_AUTORIZACAO(PER_ID, AUT_ID)
SELECT PER_ID, AUT_ID
FROM PER_PERFIL, AUT_AUTORIZACAO
WHERE PER_NOME = 'Vendedor'
AND AUT_NOME = 'ROLE_VENDA';
INSERT INTO PEA_PERFIL_AUTORIZACAO(PER_ID, AUT_ID)
SELECT PER_ID, AUT_ID
FROM PER_PERFIL, AUT_AUTORIZACAO
WHERE PER_NOME = 'Administrador';